version: '3'
services:
  database:
    container_name: incident-playground-db
    build:
      context: .
      dockerfile: docker/db/Dockerfile
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - $PWD/docker/db/data:/var/lib/postgresql/data
